language: python
python:
  - "3.6"

# Database services needed by the project

before_script:
  - pip install python-coveralls
  - pip install coverage

script:
  - coverage run --source=g_recaptcha manage.py test g_recaptcha

after_success:
  - coveralls
