language: python
python:
  - "2.7"

# Database services needed by the project

before_script:
  - pip install python-coveralls
  - pip install coverage

script:
  - coverage run --source=g_recaptcha manage.py g_recaptcha

after_success:
  - coveralls
